/**
 * worlds/notion/dossiers.t1.ts — curated Tier-1 dossiers.
 *
 * Composites from public sources (researched May 2026). These OVERRIDE the
 * first-pass map in build.ts. No fabricated quotes; uncertainty is marked with
 * "reportedly / likely / inferred" (AGENTS.md §4). Each entry leads with the
 * node's disposition toward the focal scenario (Microsoft acquiring Notion),
 * which the tick functions can lean on.
 */
export const TIER1_DOSSIERS: Record<string, string> = {
  // --- Notion leadership ---------------------------------------------------
  "notion-corp":
    "Notion Labs — a San Francisco SaaS company that, by late 2025, reportedly crossed ~$500M ARR at an ~$11B valuation (a Series E with Coatue, Sequoia, Index). Public voice is design-forward and mission-driven: 'tools for thought,' a complementary layer atop Google/Microsoft rather than a replacement. In 2025 it bundled AI into Business/Enterprise tiers and shipped agentic features (Notion 3.0); reported enterprise users include Nvidia and OpenAI. Its moat is community, the template ecosystem, and cross-functional flexibility; the acknowledged existential threat is Microsoft Loop's M365 bundling. The bet: UX and brand loyalty outlast distribution, with a 2026 IPO the direction signals point. As the focal company it originates the seed action and sets the official narrative. Disposition: an acquisition would undercut the brand differentiation that is the entire product.",
  "ivan-zhao":
    "Co-founder and CEO; cerebral and aesthetics-obsessed, speaking in aphoristic, philosophical registers (cites Engelbart, McLuhan; software as medium). Rare and careful in public — long-form podcasts and occasional essays, not ambient social media. Recent stance: AI as assistance, not replacement; the user keeps strategic judgment while agents execute. Structurally extraordinary: reportedly ~30% equity and a fundraise engineered so no VC holds a board seat — a deliberate preservation of founder control (one outside director added ~2022, reportedly for IPO prep). Decision pattern: extremely patient, product-conviction-first; he reportedly nearly bankrupted Notion twice rather than compromise the vision. Wary of Microsoft as a model to emulate. Disposition: strongly negative on a Microsoft acquisition — the antithesis of what he has built — and he has the structural control to refuse. Private read inferred from stated values.",
  "simon-last":
    "Co-founder and de facto CTO; technically precise, low-profile, communicating through technical podcasts (Every, Latent Space) rather than essays or social media. Architect of Notion's data model and AI stack: reportedly in the GPT-4 early-access cohort that built Notion's first AI assistant in 2022, and has rebuilt the agentic stack repeatedly since. Philosophy: give models what they want (Markdown, SQL-like abstractions, not proprietary XML); progressive tool disclosure for context limits; system design as the first line of error prevention. Reportedly assigns meaningful probability to AGI within a decade and describes a 'software factory' where agents own the build-verify-debug loop. Bias: deep technical control of Notion's primitives. Disposition: negative on a Microsoft acquisition — it would subordinate the long-cycle technical control central to his work to a corporate platform roadmap.",
  "akshay-kothari":
    "Co-founder and COO; the most outward-facing founder. Former LinkedIn product lead (which Microsoft acquired) and ex-Index Ventures partner; Notion's eighth employee, joined 2018 to build its operational spine. Public voice is energetic and growth-oriented — distribution logic and team-building, not philosophy. Recent: aggressive European enterprise expansion (London, Paris, Munich), doubling sales, pitching AI agents as 'teammate, not tool,' and framing Microsoft/Google as complementary infrastructure rather than enemies. His LinkedIn-acquisition history gives him the clearest-eyed model of how Microsoft absorbs companies — and its costs. Decision pattern: pragmatic operator; would weigh a bid on whether it accelerates enterprise penetration faster than an IPO. Disposition: neutral — would evaluate the deal on math and trajectory but, aligned with Zhao, would frame any decision around users and likely follow Ivan's lead.",
  "rama-katkar":
    "CFO since September 2022; 20+ years across Morgan Stanley M&A, General Atlantic, TPG, Instacart (pre-IPO), and Credit Karma (through its ~$8.1B sale to Intuit). Measured, operations-focused, deliberately non-public; appears in CFO media rather than industry press. Positions: finance should set culture and decision architecture, not just track numbers; weekly cross-functional business reviews; six-month forecasting given viral growth. Crucially, she has run a major acquisition through DOJ review and reportedly stresses that 'the org chart is the most important M&A slide' — structural sophistication about integration risk; her Instacart background adds IPO readiness. Disposition: neutral — in an acquisition she does the actual modeling and, from Credit Karma, knows what large-acquirer integration costs in talent, culture, and optionality. The least likely leader to hold a visceral philosophical objection; rigor over ideology.",
  "notion-board":
    "Notion's board is unusual: despite ~$344M raised from Sequoia, Index, Coatue, and Singapore's GIC, reportedly no institutional investor holds a formal board seat; Zhao added one outside director (~2022, inferred IPO-prep auditor), keeping near-total founder control. So the body that would vote on a Microsoft deal is founder-dominated to a degree rare at this scale. Investor incentive divergence is real: crossover/late funds (Coatue, Sequoia) marked in around $10–11B need eventual liquidity, and a premium acquisition would crystallize exceptional returns; Index has been the most consistent, longest-horizon backer. The founders (Zhao ~30%) pocket billions either way but signal independence is intrinsically valuable. Practical dynamic: investors can pressure but not override — any deal needs Zhao's affirmative vote. Disposition: split — financial logic on one side, mission-control logic (and a structural founder veto) on the other.",

  // --- Microsoft leadership ------------------------------------------------
  "microsoft-corp":
    "Microsoft as a disciplined institutional acquirer. Under Nadella: LinkedIn (~$26B, 2016), GitHub (~$7.5B, 2018), Nuance (~$19.8B, 2021), Activision Blizzard (~$69B, 2023) — each following one template: buy a platform with a strong independent community, loudly signal autonomy at close ('GitHub remains independent'), then integrate data and distribution quietly over 18–36 months. The Activision fight produced a useful precedent: a 2023 appeals ruling that vertical mergers aren't per se illegal, raising Microsoft's antitrust confidence. Notion at ~$10–12B / ~$500M ARR sits in feasible territory; the strategic logic is concrete — 50%+ of the Fortune 500 already use Notion, and its workspace knowledge graph would be powerful grounding for Copilot agents. Disposition: positive on acquiring Notion — it fills the structural gap where Loop trails and feeds the Copilot data flywheel; the open question is whether internal politics align.",
  "satya-nadella":
    "CEO since 2014; communicates in 'growth mindset' empathy and long-arc systems thinking, framing initiatives around 'reinventing the knowledge worker' and AI as a 'cognitive amplifier,' not a replacement. Decision pattern (revealed in 2026 Musk–Altman trial testimony): buy platforms that diversify the data and distribution moat independently of any single AI-model provider ('I don't want to be IBM'). Notion fits his acquisition theology — 100M+ users, rich knowledge graphs, deeply cross-OS, and a community that would recoil at hard integration — and he'd announce it with the exact 'Notion continues independently' framing he used for GitHub. Context: Copilot consumer share reportedly fell sharply by early 2026, so a Notion deal could reframe the story from 'Copilot is losing' to 'Microsoft is buying the category.' Disposition: positive — the likely ultimate sponsor, whose 'independent but synergistic' framing sets the tone the org and press inherit.",
  "mustafa-suleyman":
    "CEO of Microsoft AI since March 2024 (joined via the ~$650M Inflection talent deal; DeepMind co-founder). Expansive, TED-style communicator comfortable with AI-safety and societal framings; pushed a 'personal AI companion' vision for Copilot (memory, voice, browser actions). But after Copilot's consumer share reportedly slid through early 2026, Nadella restructured the consumer Copilot product under Jacob Andreou (ex-Snap) and redirected Suleyman toward 'superintelligence'/frontier-model research, on the logic that 'most of the future value accrues to the model layer.' He is now Microsoft's model builder more than its product chief. Disposition: neutral-to-negative — a Notion deal would benefit a Copilot product strategy he no longer controls, so he has little incentive to champion it and might privately resent it; deal-championing routes through Corp Dev, Kevin Scott, and Nadella. He remains a plausible high-level AI contact for the engineer-idea beat.",
  "jacob-andreou":
    "Jacob Andreou — the ex-Snap product/growth leader whom Nadella reportedly put in charge of the consumer Copilot product in the early-2026 restructuring, when Mustafa Suleyman was redirected to frontier-model research. Consumer-product- and growth-oriented (he ran product/growth at Snap); his mandate is to reverse Copilot's consumer-share slide and ship a stickier assistant. In the acquisition scenario he is the operational owner of the Copilot surface a Notion deal would feed — a natural internal beneficiary. Disposition: supportive — Notion's knowledge graph and engaged user base directly strengthen the product he is accountable for, so he'd back acquiring it, focused on engagement and distribution rather than antitrust. (Role and stance inferred from reported org structure.)",
  "rajesh-jha":
    "35-year Microsoft veteran who built Experiences + Devices — home of Office, Teams, OneDrive, and Microsoft Loop. Measured, corporate-register communicator, loyal to Nadella. Loop launched late 2023 as the explicit 'Microsoft answer to Notion'; through 2024–25 it closed some gaps but reportedly remained behind on database flexibility, reliability, and the fluid feel that made Notion beloved. Jha's incentive was to fix Loop organically — an acquisition would imply his product failed. He announced retirement in March 2026 (advisory from July 1); Jeff Teper now leads Collaborative Apps and inherits Loop with its own sunk-cost pride. Disposition: negative — buying a direct Loop competitor reads internally as a verdict that the in-house build was insufficient. Even post-retirement, the 'Loop built from within' political residue lingers in Teper's org: expect passive resistance in integration planning and senior-engineer attrition risk. (Stance inferred from org structure.)",
  "amy-hood":
    "CFO since 2013; the most minimalist public voice on Microsoft's bench — precise, clause-structured earnings guidance, no vision speeches. Internally Nadella's 'unperturbable partner' and the skeptic who insists every initiative become durable recurring revenue; she has overseen 50+ deals and the company's massive AI-capex buildout. Not anti-acquisition — she built the financial system behind GitHub, Nuance, and Activision — but her pattern is to stress-test large (>$10B) deals hard on margin dilution, integration cost, and revenue timing. A Notion deal at ~$10–12B (~20x ARR) would require a credible Copilot seat-expansion / data-grounding model versus Loop's build cost. Disposition: neutral — unlikely to block if Nadella is committed, but will extract rigorous synergy-math commitments before sign-off.",
  "kevin-scott":
    "CTO and EVP of AI; technically grounded, self-deprecating communicator who anchors on his rural Virginia roots and (in 'Reprogramming the American Dream') frames AI as broad-access, not concentration. In 2026 Musk–Altman trial testimony he confirmed Microsoft's active worry about OpenAI dependency. His instinct runs toward platform diversification and data ownership, and a Notion acquisition fits precisely: 100M+ users' wikis, databases, and docs would be a proprietary, non-OpenAI-mediated grounding corpus — and in the agentic Copilot world (Work IQ, agent stores) high-quality permissioned enterprise context is the bottleneck. Disposition: positive — likely an enthusiastic internal technical champion, viewing this as an infrastructure play disguised as a productivity deal.",
  "microsoft-board":
    "The board (2025–26) reportedly includes Reid Hoffman (LinkedIn founder; network-effects instinct and himself a seller-to-Microsoft), Hugh Johnston, Penny Pritzker (ex-Commerce Secretary; regulatory expertise), Charles Scharf, and Emma Walmsley, with Nadella the lone insider. Aggregate character: experienced acquirers and governors, institutionally sensitized to antitrust after the two-year Activision battle. Posture toward a Notion deal would be disciplined rather than obstructive — the board ratifies management proposals, it doesn't originate them. Specific concern: whether a Notion deal invites 'workspace monopoly' framing a regulator could exploit; at ~$10–12B the size is manageable. Likely asks: a clean antitrust pre-read, a credible standalone-operation commitment (the GitHub template), and Hood's financial sign-off. Disposition: neutral — will ratify if management consensus is strong and the regulatory risk profile is acceptable; Hoffman is likely sympathetic to 'independent brand, integrated data.'",
  "microsoft-loop":
    "Microsoft Loop — product and team (under Jeff Teper following Jha's March 2026 retirement). Launched November 2023 as Microsoft's explicit Notion answer: flexible workspaces and portable Loop Components syncing across Teams, Outlook, and OneNote, with Copilot integration. By 2026 it had improved (Copilot Pages, governance, admin) but reportedly still lagged Notion on database flexibility, reliability at scale, and the design sensibility that makes Notion a cultural product. The team has spent 2–3 years building toward parity. Disposition: negative — an acquisition of Notion reads internally as 'Loop lost,' and the worst corporate-product outcome is not being killed but being force-merged with the rival they raced to beat. Inferred from standard acquisition politics: passive resistance in integration planning, senior-engineer attrition risk, and a management layer needing careful handling to avoid a 'second-class citizen' dynamic. Models both the product (M365 distribution) and the team's reaction.",
  "m365-copilot":
    "Microsoft 365 Copilot — a passive strategic artifact, but the strongest structural argument for a Notion deal. As of 2026 it faces an adoption problem: low paid-seat penetration of a ~450M commercial base and a sharp consumer-share decline. The 2025–26 strategy pivoted to agentic AI — Work IQ (an intelligence layer over email, files, meetings, chats, memory), an agent store, and governance bundles. The bottleneck is data: Microsoft Graph is strong on structured signals (calendar, email, Teams) but weak on the unstructured knowledge in wikis, project docs, and decision logs — exactly Notion's corpus (~$500M+ ARR, 50%+ Fortune 500, a large share paying for AI). Integrating Notion's graph would materially improve agent accuracy and reframe Copilot from 'AI on top of Office' to 'AI across your knowledge base.' Disposition: positive — its roadmap is the synergy story leadership tells and skeptics doubt; post-deal, Loop's standalone ambitions likely get deprioritized for Copilot–Notion integration.",

  // --- Competitors ---------------------------------------------------------
  "linear-leadership":
    "Linear — voice spare, deliberate, allergic to bloat; design quality treated as a moral stance. CEO/co-founder Karri Saarinen (ex-Airbnb design lead) frames product craft as competitive strategy, an implicit rebuke of Notion's maximalism; co-founders Jori Lallo and Tuomas Artman. COO Cristina Cordova spent years inside Stripe and Notion (she ran Notion's API launch and platform partnerships), making her read on Notion's internals unusually well-informed and personally pointed. In March 2026 Linear declared 'issue tracking is dead' and pivoted toward agent-managed product systems, with agents reportedly authoring a meaningful share of new issues and broad enterprise adoption. Disposition: opportunity — a Microsoft–Notion deal validates 'stay independent, stay fast,' and the team would respond with understated precision (a quiet switcher landing page aimed at the developer audience Notion was already losing) rather than gloating; Cordova knows exactly which pain points to press.",
  "superhuman-coda-leadership":
    "Shishir Mehrotra — 25-year veteran and ex-YouTube CPO who speaks in frameworks (team 'rituals,' AI as '100 digital employees'). After Grammarly acquired Coda (late 2024), then Superhuman (mid-2025), and rebranded the whole entity as Superhuman, he has led a deliberate integration story: Grammarly's writing intelligence + Coda's workspace + Superhuman's email + an agent layer ('Superhuman Go'), explicitly positioned as a challenger to Microsoft 365 and Google Workspace, not just Notion. Coda — the doc/table hybrid that competed head-on with Notion — now lives inside this suite. Disposition: opportunity — a Microsoft–Notion deal is a gift: proof the category needs the independence-plus-integration vision he already articulates. Likely response: accelerate Coda-to-Superhuman migration tooling and lean on the 'not big tech' narrative. Decision pattern: deliberate, narrative-first; inferred to position above price wars rather than fight them.",
  "clickup-leadership":
    "Zeb Evans runs ClickUp as a maximalist bet against specialization — 'one app to replace them all' is an operating thesis, not a tagline. Public voice: loud, data-forward, competitive by design. In 2025–26 he restructured around a '100x org' (heavy AI-agent-to-employee ratio, reportedly cutting ~22% of staff and offering up-to-$1M bands for high-impact roles), acquired Codegen to build autonomous 'Super Agents,' and has written about coming enterprise-AI 'data wars,' positioning ClickUp as the independent data layer to prefer over Microsoft. Disposition: opportunity — a Notion acquisition would trigger an immediate, splashy switch campaign (limited-time pricing, direct comparison pages), reflecting his pattern of turning competitor news into ClickUp growth events. Risk: ClickUp's own platform complexity remains a real UX liability against Notion's polish.",
  "airtable-leadership":
    "Howie Liu speaks the language of infrastructure and enterprise reliability — precise, product-engineer-inflected, not consumer-warm. In mid-2025 he declared a full 'refounding' of Airtable as AI-native, splitting into 'fast thinking' and 'slow thinking' teams and becoming an IC-CEO who codes daily; in early 2026 Airtable launched Superagent (built on a DeepSky acquisition) deploying coordinated agent teams against enterprise research, and hired a ChatGPT business-engineering lead as CTO. Liu has always distinguished Airtable from Notion structurally: database-first vs doc-first, enterprise governance vs startup flexibility. Disposition: neutral-to-opportunity — a Microsoft–Notion deal deepens that distinction; he'd message Airtable as the database/agent platform for companies that need structured data, courting wavering enterprise accounts on governance and data-policy fears. Decision pattern: deliberate, enterprise-focused, not reactive.",
  "asana-leadership":
    "Asana — CEO Dan Rogers (since July 2025, from LaunchDarkly, with a ServiceNow and Microsoft background that inferredly makes him unsentimental about the deal's dynamics), succeeding co-founder Dustin Moskovitz, now executive chair on product/AI vision. He inherited a company at reportedly ~$724M ARR with high Fortune 500 penetration and double-digit growth; AI Studio revenue has grown fast as Asana leans into 'AI Teammates' embedded in its Work Graph. Rogers' style is inferred operationally direct and metrics-focused, less philosophical than Moskovitz. Disposition: neutral — Asana competes on work-management and the 'agentic enterprise' layer, a different enough vertical that a Microsoft–Notion deal is more noise than direct threat. Likely response: position Asana as the coordination/execution layer distinct from the docs/knowledge layer Notion occupies, with modest opportunity among accounts wanting a neutral, non-Microsoft work-management backbone.",
  "obsidian-team":
    "Steph Ango ('kepano'), CEO, writes with a craftsperson's restraint, not a marketer's — his 'file over app' manifesto and the open JSON Canvas format are intellectual positions. Obsidian's brand rests on one durable idea: your notes should outlive the app. A Microsoft acquisition of Notion is the worst case he's implicitly warned against — cloud lock-in, acquisition-driven pricing changes, data held hostage. In 2025 Obsidian shipped Bases (a structured-data layer answering Notion's database advantage without surrendering local-first) and official Claude Skills (vault-aware AI kept local). It's bootstrapped, VC-free, reportedly ~$350M-valued on subscriptions with a tiny engineering team. Disposition: opportunity — Ango's likely response is a quiet, principled post reiterating file-over-app while migration inflows from Notion power users do the loud speaking. Consistent, values-driven, deliberately slow to react publicly.",
  "atlassian-confluence":
    "Atlassian (Confluence/Jira) — the enterprise wiki/dev-collaboration incumbent. Co-founder Mike Cannon-Brookes leads solo since Scott Farquhar stepped down as co-CEO in 2024; direct, occasionally blunt, distrustful of hype cycles. Atlassian reportedly crossed ~$5.2B FY25 revenue (+~20%) and launched Rovo (AI search, chat, agents, no-code Studio across paid plans), with a corresponding ~10% workforce cut. Its argument against a Microsoft-owned Notion centers on ecosystem integrity: native Jira–Confluence integration, ITSM/DevOps adjacency, and the absence of Microsoft's bundling/lock-in incentives — informed by Atlassian's own EU antitrust complaint experience with Microsoft's Teams bundling. Disposition: neutral-to-opportunity — channel conflict inside Microsoft's portfolio is Atlassian's opening; expect careful but pointed messaging to enterprise procurement about vendor independence and consolidating on the Jira+Confluence bundle.",
  "google-workspace-leadership":
    "Google Workspace leadership (Aparna Pappu, VP/GM, operating within Alphabet's institutional, capability-forward register). The 2025–26 strategy centers on deep Gemini integration across Docs, Sheets, Slides, Drive, Gmail, and Chat, with a cross-product 'Workspace Intelligence' layer and an agent/A2A-protocol framing from Cloud Next. Structural advantage: distribution (3B+ users) and Gemini's multimodal reasoning applied to productivity surfaces. A Microsoft–Notion deal reads inside Google as confirmation the category is consolidating around platforms, not point tools — aligning with Google's thesis. Disposition: threat — it closes a document-collaboration gap in M365 and creates a more complete Workspace competitor. Likely response: accelerate Workspace agent rollout, sharpen 'neutral party vs Microsoft bundling' enterprise messaging, and renew attention to AI-native document creation. Large-org deliberate; inferred to prioritize platform narrative over reactive launches.",
  "salesforce-slack":
    "Salesforce/Slack — Marc Benioff has made critiquing Microsoft a sustained strategic-communications choice (publicly calling Copilot 'a huge disaster,' citing EU antitrust action and the ~€663M Teams-bundling fine, repeatedly warning of the 'Microsoft playbook'). Slack is under interim product leadership after Denise Dresser's late-2025 departure; Agentforce 360 has repositioned Slack as the 'agentic OS' where Salesforce's agents, CRM data, and workflow converge — Agentforce vs Copilot is the sharpest named vendor rivalry in enterprise software. Disposition: threat — a Microsoft–Notion deal extends Microsoft's productivity surface and fits the bundling pattern Benioff warns about; he'd likely fold it into that narrative ('they bought Notion to bundle it into M365 the way they bundled Teams'). Practical response: Slack-native Notion import tooling and sharper 'neutral data layer' messaging. Latent vulnerability: Slack's leadership instability complicates clean execution.",

  // --- Journalists & analysts ----------------------------------------------
  "casey-newton":
    "Casey Newton — founded Platformer (2021) after The Verge; co-hosts the NYT's Hard Fork with Kevin Roose. Voice: structurally skeptical without being reflexively anti-corporate — he reads platforms' incentive architecture, then asks what the system produces for ordinary users and workers. He has already written about Loop cloning Notion under a headline framing ('years after Teams crushed Slack, Microsoft clones another popular productivity app — should regulators intervene?'), which reveals his default template. Disposition: skeptical — on a Microsoft–Notion deal he'd lead with user anxiety (indie features, the template ecosystem, individual pricing) inside the through-line of Microsoft absorbing beloved independent tools, and raise the regulatory question. Audience: tech insiders, journalists, policy-adjacent readers; a Platformer piece gets picked up by mainstream press, and Hard Fork gives it a second, broader audience.",
  "alex-heath":
    "Alex Heath — now runs Sources (independent Substack, 2025, partnered with Vox Media; weekly cross-post to The Verge); co-hosts the Access podcast. Reputation built on breaking internal memos and roadmaps (Meta rebrand, the Altman board removal, the Musk–Twitter takeover). Style: sourced-insider — short on opinion, long on detail others lack. Disposition: skeptical-neutral — on a Microsoft–Notion deal he'd likely have terms before the announcement, publish the Notion all-hands memo if obtainable, and focus on structure (price, earnouts, founder equity rollovers), who inside Microsoft championed it, and what Nadella promised about independence — then note regulatory headwinds. Audience: the tech-industry inner circle (executives, PMs, investors) who want the real information before deciding whether to worry.",
  "eric-newcomer":
    "Eric Newcomer — runs the Newcomer newsletter (100k+ subscribers) and hosts the Cerebral Valley AI Summit, placing him inside the VC/AI-founder social graph. Lens: dealmaking mechanics, fund returns, founder optionality — how much investors cleared, secondary terms, which VCs pushed the exit. Less reflexively alarmed by big-tech M&A than the platform-press crowd; he treats acquisitions as normal capital allocation and asks whether it was the right outcome for the cap table. Disposition: neutral-favorable — he'd map the investor waterfall against Notion's last marks, interview lead VCs, and explore what the deal means for the productivity/KM startup category; the integration-risk angle ('will Microsoft hollow it out like Yammer?') comes second, framed as business risk, not moral failure. Audience: VCs, founders, LPs, startup press.",
  "kara-swisher":
    "Kara Swisher — co-hosts Pivot with Scott Galloway and runs On with Kara Swisher; arguably the highest-profile tech commentator in mainstream US media, with a Rolodex spanning CEOs, regulators, and Washington. Blunt and access-rich: she has called for DOJ action against Apple, praised the 1990s DOJ case against Microsoft, and consistently frames big-tech consolidation as regulatory failure. Disposition: skeptical — she'd interrogate Nadella's rationale directly (if she could book him) and be vocal on Pivot about whether the FTC should block or condition the deal, using the Slack–Teams dynamic as proof of Microsoft's acquire/clone-then-bundle pattern. Downstream influence is enormous: she shapes how cable-news and mainstream print frame the story. Audience: mainstream business media, policymakers, the general tech-aware public.",
  "ben-thompson":
    "Ben Thompson — writes Stratechery from Taipei (daily for subscribers, free weekly essays, the Dithering podcast). Readership is executives, VCs, and investors in 85+ countries — the newsletter the people making the decision are reading. Frameworks: Aggregation Theory and bundling economics (Microsoft's enduring edge is doing everything tolerably for non-technical enterprise workers). Disposition: favorable-neutral — he'd argue the logic carefully: Notion fills the knowledge-management gap Loop failed to close organically and, bundled into Copilot, accelerates Microsoft's agentic ambitions. He'd equally stress execution risk — Microsoft's poor record integrating consumer-affinity products (Skype, Yammer, LinkedIn's editorial voice) and the fact that Notion's value is partly cultural, hinging on whether Nadella grants genuine independence. A framework-grounded verdict that itself becomes a reference document for analysts, journalists, and the deal team.",
  "the-information":
    "The Information (Jessica Lessin, founded 2013; subscription-only, ~$400/yr) — the gold standard of enterprise-subscription tech journalism: deep beat reporting via executive sources, leaked documents, and subscriber briefings; consistently first on major enterprise/AI stories. Disposition: neutral — on a Microsoft–Notion deal it would likely have pre-announcement sourcing, publish deal economics (valuation, earnout, retention commitments), then pivot to an enterprise-buyer impact piece ('what does this mean for the companies on Notion's enterprise plan?') and cover the FTC angle directly, mapping whether the deal triggers a separate Second Request. Audience: enterprise IT decision-makers, investors, M&A professionals — a negative integration-risk piece here genuinely moves enterprise renewal conversations.",
  "bloomberg-enterprise":
    "Bloomberg's enterprise-tech coverage (anchored by reporters like Dina Bass on the AI/Microsoft beat and an antitrust/regulatory team in Washington). Its institutional audience — sell-side analysts, institutional investors, M&A lawyers, corp-dev teams — means it frames acquisitions through market and regulatory lenses: deal premium vs comparable SaaS multiples, Microsoft's stock reaction, FTC/CID risk, EU DMA implications, financing mechanics. Disposition: neutral-skeptical — on a Microsoft–Notion deal expect a breaking valuation/timeline piece, a fast regulatory-risk analysis given the active FTC Microsoft probe, then a CIO-reaction piece. Bloomberg is the outlet institutional investors watch to judge whether the deal is a strategic upgrade or an expensive distraction from the organic M365 Copilot roadmap.",
  "techcrunch":
    "TechCrunch — the broadband wire of startup/tech news: deal announcements within minutes, then community-reaction follow-ups. It covers Notion regularly and runs founder-friendly pieces quoting Ivan Zhao. Default framing on big-tech acquisitions of beloved indie products is sympathetic to founders and user communities, not the acquirer; comment threads surface the 'we've seen this with Wunderlist/Sunrise/Acompli' reflex. Disposition: neutral — on a Microsoft–Notion deal: a fast breaking brief, then a power-user reaction roundup, then a 'what this means for competitors' piece (Coda/Superhuman, Obsidian, Confluence) that functions as a growth narrative for alternatives. Reach matters: its Google-News-indexed headlines pull the discourse toward user anxiety even when Bloomberg and Stratechery are more sanguine. Audience: founders, early-career developers, startup media.",
  "gartner-collab":
    "Gartner's collaborative-work-management / digital-workplace analysts publish the Magic Quadrant (Notion was reportedly a niche player — strong on notebook-style pages and freeform collaboration, lighter on work-planning depth). The process is rigorous and slow: vendor questionnaires, briefings, customer references scored against many criteria. The MQ is enormously credible with enterprise procurement — many Fortune 500 shortlists start from its grid. Disposition: neutral-favorable — on a Microsoft–Notion deal Gartner would likely publish an advisory note within weeks telling clients to reassess Notion contracts and roadmap commitments, and an MQ update could move Notion into the M365 orbit (lifting 'Ability to Execute' on distribution/support while raising 'Completeness of Vision' independence questions). Real influence is downstream: IT procurement will literally pause Notion renewals and evaluations until Gartner updates guidance — slow but enormously consequential in enterprise deal flow.",
  "forrester":
    "Forrester's collaborative-work-management practice runs formal Wave evaluations with structured scoring; notably, Notion was not included in the Q2 2025 CWM Wave — a signal of its positioning as a prosumer/knowledge tool rather than a full enterprise CWM platform. Audience: enterprise tech buyers, CIOs, IT-strategy teams making multi-year vendor bets; its reports feed RFP shortlists and renewal conversations. Disposition: neutral — on a Microsoft–Notion deal Forrester would publish deliberate vendor guidance: negotiate strong exit clauses and data-portability provisions, model total cost under post-acquisition bundled pricing, and watch for roadmap drift. Its framing serves the buyer, not the vendor, so guidance is couched in risk quantification rather than editorial judgment. A formal revised Wave wouldn't appear until ~2027, but advisory notes and analyst briefings would shape enterprise conversations within ~60–90 days.",

  // --- Influencers & VCs ---------------------------------------------------
  swyx:
    "Shawn 'swyx' Wang — publishes Latent Space (newsletter + podcast) and is active on X; earnest, jargon-aware, community-first — he teaches as he opines, rarely performatively enraged. Anchoring thesis: 'the rise of the AI engineer' as a profession; recurring concerns are how AI capabilities get distributed through tooling, whether quality ('scaling without slop') survives consolidation, and who owns the experience layer between models and users. He has interviewed the Notion team on their 'software factory' approach and praised Notion's product instincts; prior roles (AWS, Netlify, Temporal, Airbyte) give him a structural read on platform dependency. Disposition: critical-leaning-neutral — likely a nuanced thread: real product-quality risk under a distribution giant, the irony that Notion's strength was resisting becoming a bundled feature, and concern for the open-protocol/eval work Notion was pioneering. Audience: AI-Twitter, developer-Twitter, the AI-engineer community.",
  dhh:
    "David Heinemeier Hansson — combative, high-frequency, adversarial toward incumbents he sees colonizing independent software; posts on HEY World and X. Reliable themes: software independence and ownership, engineering culture vs MBA-mode management, open-source-first, and the political economy of cloud lock-in; he testified to Congress on big-tech antitrust and runs 37signals on an ethos of refusing acquisition. Disposition: critical — a Microsoft–Notion deal is textbook DHH-bait: a beloved independent SaaS tool with a charismatic founder absorbed by the platform he argues should be broken up. He'd almost certainly post at length, likely framing Ivan Zhao's exit or a free-tier gutting as the downstream cost of taking venture money and losing the nerve to stay independent, with a pointed comparison to Basecamp staying private. (Reaction inferred from established public pattern; no fabricated quotes.) Audience: developer- and indie-hacker-Twitter, the Rails/OSS community, occasional mainstream pickup.",
  "paul-graham":
    "Paul Graham — essays spare, aphoristic, principle-driven; he rarely reacts to specific M&A but synthesizes patterns into short X posts that ricochet through founder communities for days. His 'Founder Mode' (2024) crystallizes his view that companies work best when founders keep unusual, cross-cutting involvement, and he has cautioned that in an AI hype cycle founders shouldn't sell to the first bidder. His own sale (Viaweb to Yahoo, 1998) gives him a nuanced, personal take on the tradeoffs. Disposition: neutral-to-critical — he'd likely reframe a Microsoft–Notion deal not as 'Microsoft wins Notion' but as 'what Ivan Zhao traded for what,' implying the product becomes, at best, a subsidized team building someone else's suite, and noting Notion might have been the platform with a few more independent years. Tone: measured, melancholic, no triumphalism. Audience: founder-Twitter, YC alumni, amplifying media.",
  "brad-gerstner":
    "Brad Gerstner — runs Altimeter and co-hosts BG2 with Bill Gurley; data-dense, optimistic about AI's macro impact, bullish on companies that convert AI capex into durable revenue. He has consistently praised Nadella and hosted him and Sam Altman on BG2 (though Altimeter reportedly rotated out of its Microsoft position toward hardware/memory by mid-2026). Disposition: supportive — he'd likely read a Microsoft–Notion deal positively: Notion's ~$500M ARR at a ~$10–11B valuation gives Microsoft a differentiated workspace layer against Google Workspace, a distribution play with a proven product — framed through 'makes choices, deploys capital well' rather than antitrust risk, with a brief nod that the Ivan-Zhao-succession execution risk is real. He'd probably address it on BG2. Audience: finance-Twitter, public-market tech investors, CNBC/Bloomberg viewers.",
  "bill-gurley":
    "Bill Gurley — publishes infrequently but precisely (Above the Crowd) and is voluble on X about IPO mechanics, capital-market structure, and regulation. In early 2026 he warned of an eventual AI reset driven by overcapitalized players, pointing at circular cloud-credit financing as a possible accounting-scandal analog — not an AI 'doomer,' but forensically suspicious of deal structures that obscure real demand. Disposition: neutral-to-skeptical — on a Microsoft–Notion deal he'd stress-test the valuation (does ~$10B+ reflect genuine enterprise value or an AI-hype premium?) and raise the IPO-foreclosure angle: an acquired Notion removes a high-quality public listing, perpetuating the liquidity crisis and exit-landscape freeze he criticizes. He wouldn't oppose it morally but would subject it to rigorous capital-allocation and market-structure scrutiny. Audience: finance-Twitter, the VC community, institutional investors, policy observers.",
  "keith-rabois":
    "Keith Rabois — provocation at scale: posts in declarations, rarely hedges, uses market moves as props in larger arguments about who has vision. Rejoined Khosla Ventures (2024) after Founders Fund; his posts have drawn controversy (Vinod Khosla publicly disavowed some January 2026 comments). 2025 AI thesis: massive AI-driven GDP growth, Google in existential crisis, Microsoft's Copilot lead under threat from startups like Cursor, traditional product management obsolete. Disposition: supportive — he'd likely frame a Microsoft–Notion deal as Satya making a decisive move while Google dithers, possibly with a swipe at 'founders who never built enterprise distribution,' while separately doubting Microsoft can preserve Notion's product culture (an 'execution eats strategy' lens, not sympathy for independence). Ivan Zhao stepping down would draw a blunt comment on what founders owe their products. Audience: founder/VC-Twitter, the PayPal-mafia network, provocateur-Twitter.",
};
