/**
 * worlds/anthropic/dossiers.t1.ts — curated dossiers (Tier-1 + the three
 * ideological-community clusters). Composites from public sources (researched
 * May 2026); the most specific figures are hedged ("reportedly"); uncertainty
 * marked ("likely / inferred"); no fabricated quotes (AGENTS.md §4). Ids here are
 * CURATED — build.ts uses them verbatim and gen-dossiers.ts skips them.
 */
export const CURATED_DOSSIERS: Record<string, string> = {
  // --- Anthropic leadership & company --------------------------------------
  "anthropic-corp":
    "Anthropic PBC — a safety-focused frontier lab founded 2021 by seven ex-OpenAI researchers who left over safety-vs-commercialization disagreements. Maker of Claude; pioneered Constitutional AI and the Responsible Scaling Policy (RSP); the self-styled 'safety-first' lab. Reportedly closed a ~$30B Series G at a ~$380B valuation (Feb 2026, GIC/Coatue); Amazon committed up to ~$25B plus a ~$100B AWS/Trainium pact, Google up to ~$40B plus ~1M TPUs; annualized revenue reportedly ~$43B by April 2026 across 300k+ business customers. Core strain is now lived, not theoretical: in Feb 2026 it revised the RSP to drop the hard pause-on-development pledge (citing competitive collective-action), resisted Pentagon pressure on autonomous-weapons safeguards, and saw a safeguards-research lead resign. Disposition: meets an incident with transparency-as-strategy, a raise as compute fuel, regulation with cautious support, a launch as proof a safety lab can lead. Figures reportedly per public reporting.",
  "dario-amodei":
    "Co-founder and CEO; ex-OpenAI VP of Research. Intellectually dense, morally grounded, deliberately measured — he argues through long essays ('Machines of Loving Grace,' 2024; 'The Adolescence of Technology,' 2026) rather than spokespeople. Predicts 'powerful AI' could arrive within one to two years and frames that as requiring immediate institutional response; explicitly rejects both doomerism and dismissiveness, casting Anthropic as the actor best able to navigate the gap. Decision pattern: rationalizes procedural flexibility as safety-preserving when unilateral restraint would just cede ground — he reportedly approved the 2026 RSP overhaul on collective-action grounds — but is reportedly firm on weapons and surveillance red lines. Disposition: the moral-authority voice across the storylines; transparent on an incident, mission-justifying on a raise, careful that a launch reads as safe capability. Private views inferred from public writing.",
  "daniela-amodei":
    "Co-founder and President; Dario's sister; ex-OpenAI (safety/policy & ops) and ex-Stripe. Owns operations, strategy, partnerships, people, and culture while Dario leads research and policy. Public presence is interview-driven — warm, measured, oriented to institutional craft over AI-risk theory (she has argued humanities skills and 'soft skills' grow more valuable as AI handles technical work). Has overseen hypergrowth from a research boutique to a company reportedly serving 300k+ business customers, and describes Anthropic as 'part research lab, part tech startup' with a public-benefit mission. Disposition: in a co-founder-departure or safety incident she is the steward of internal trust and the culture narrative; in a mega-raise she manages the strain between the idealistic founding story and a ~$380B business with Amazon and Google as major stakeholders. Internal specifics inferred from public profile.",
  "jared-kaplan":
    "Co-founder and Chief Science Officer; also Responsible Scaling Officer since late 2024. A theoretical physicist, lead author of the 2020 scaling-laws work that became the intellectual license for the frontier race. Academic in register, sparse in the press. He was publicly candid about the 2026 RSP overhaul — reportedly telling TIME that it 'wouldn't actually help anyone for us to stop training AI models' if competitors keep scaling. Decision pattern: pushes for internal safeguards and eval rigor but is structurally biased against unilateral capability restraint, viewing interpretability and alignment research (not deployment pauses) as the right lever. Disposition: weighs a launch on genuine capability and evals; in an incident he explains the technical reality. The internal tension: he both created the scaling-race incentive and now polices it.",
  "tom-brown":
    "Co-founder; leads Core Resources — compute infrastructure, training operations, the physical substrate of Claude. Lead author on GPT-3 (2020) before leaving OpenAI with the Amodei cohort. Rare in public; when he appears he speaks as an engineer's engineer — concrete, systems-oriented. Has described the AI compute buildout as larger than Apollo and the Manhattan Project combined, with roughly 3x annual spend growth. Disposition: central to a model launch (the training run) and a mega-raise (compute is the use of funds); pragmatic about the Amazon Trainium / Google TPU dependencies. A quiet but critical node — his read on infrastructure feasibility shapes which timelines are credible and which safety-relevant training iterations are actually attempted. Details inferred from public background.",
  "chris-olah":
    "Co-founder; originator of Anthropic's mechanistic-interpretability program — reverse-engineering networks into human-readable features and circuits, and the driver of the Transformer Circuits thread. Communicates through meticulous, diagram-rich write-ups; publishes slowly but influentially, prioritizing conceptual clarity. Anthropic's 'Scaling Monosemanticity' work and the public 'understand most model issues by 2027' goal flow from this program. Disposition: the least commercially oriented co-founder and the most likely to flag a safety concern early. A safety incident would validate and likely accelerate his program; he would be skeptical of RSP softening that isn't backed by interpretability evidence that risks are genuinely understood — making him the archetypal safety co-founder whose (hypothetical) departure would signal the balance breaking. Views inferred from public writing.",
  "jack-clark":
    "Co-founder and Head of Policy; author of the widely-read Import AI newsletter (reportedly 116k+ subscribers since 2016); ex-OpenAI policy and ex-Bloomberg journalist. His voice is simultaneously technical and geopolitical — a defense-analyst register applied to arxiv. In May 2026 he published an 'intelligence explosion' warning (reportedly a 60%+ chance AI systems train their successors autonomously by end-2028) and called for coordinated, sector-by-sector deployment 'dials.' He has testified before Congress and pushed international-coordination frameworks. Disposition: the front line for a regulation scenario (Anthropic is comparatively pro-some-regulation) and for incident comms; likely the internal voice most insistent on publishing hard institutional warnings even against near-term commercial optics — and Import AI is a megaphone the company cannot wholly control.",
  "mike-krieger":
    "Chief Product Officer (joined May 2024); Instagram co-founder (scaled it past a billion users) and ex-Artifact. In Jan 2026 he was moved into a new 'Labs' group for experimental products; in April 2026 he resigned from Figma's board the same day reporting said an upcoming Claude (Opus 4.7) would add competing design tools — a clean-hands move with obvious subtext. Public voice: product-manager conversational — building AI products 'from the bottom up,' scaling without losing craft. Disposition: the internal advocate for consumer-facing Claude experiences, lower friction, and product velocity — the commercial counterweight to a research culture that prefers caution and publication-paced iteration. A model launch is his showcase; a safety incident complicates it. Remit inferred from public role.",
  "amazon-investor":
    "Amazon — the most structurally integrated investor. Reportedly committed up to ~$25B (atop a prior ~$8B), with Anthropic committing $100B+ in AWS spend over ten years; the backbone is Project Rainier (reportedly ~500k Trainium2 accelerators) scaling toward ~5GW. Anthropic is the anchor tenant validating Amazon's custom silicon against Nvidia — every Claude run on Trainium is proof-of-concept. The dependency is symmetric: AWS capacity shapes which model generations are possible and when. Disposition: backs raises and scale, wants Claude winning on AWS Bedrock with strong enterprise traction; an incident or heavy regulation is a commercial risk to manage, not a mission concern — and Amazon's DoD cloud relationships likely add indirect pressure on Anthropic's military-use red lines. Terms reportedly per public reporting.",
  "google-investor":
    "Google/Alphabet — reportedly committed up to ~$40B (cash plus compute-milestone-contingent), with access to up to ~1M TPUs and a multi-year Cloud spend on the order of ~$200B. The logic is layered: Anthropic's TPU consumption validates Google's Trillium/Ironwood chips, hedges Nvidia dependence, and lends Google a 'safety-focused' narrative alongside Gemini. The tension is structural — Google DeepMind competes directly with Anthropic for frontier leadership, enterprise customers, and talent, and Google reportedly booked ~$10B in paper gains on the stake in Q1 2026. Disposition: a frenemy — financially supportive of raises and capability deployment (its interests push toward revenue, not precautionary pauses), but the DeepMind rivalry keeps interests only partly aligned. Terms reportedly per public reporting.",

  // --- Rival labs ----------------------------------------------------------
  "openai-altman":
    "Sam Altman / OpenAI — the primary, foundational rival: Anthropic's founders are OpenAI defectors, so every benchmark is a referendum on who was right. Brash, vision-forward, comfortable with contradiction — championing safety frameworks while reportedly removing 'safely' from the mission and taking defense contracts Anthropic declined. In 2026, GPT-5.5 reportedly leads on several agentic/math benchmarks while Claude Opus 4.7 reportedly leads SWE-Bench Pro and Humanity's Last Exam; the Musk trial (which OpenAI won) reinforced Altman's survivor image. Disposition: rival — would answer an Anthropic safety incident with swift, polished positioning (a well-timed post on OpenAI's own frameworks), treat an Anthropic raise as a signal to accelerate, and likely trigger a 'code red' internal sprint against a leap-ahead Claude. Internal specifics inferred.",
  "google-deepmind":
    "Demis Hassabis / Google DeepMind — measured, scientifically grounded, talks in geological timescales (reportedly declared 'we're at the foothills of the singularity' at I/O 2026). Real safety credibility (a Frontier Safety Framework, a UK government research partnership) alongside Gemini's rapid cadence; Google has acknowledged its coding tools trailed Anthropic/OpenAI and answered with a Claude Code challenger ('Antigravity'). Disposition: a frenemy — Google is an Anthropic investor while DeepMind competes head-on at the frontier and for talent. Would answer an Anthropic incident with carefully worded, structurally similar safety commitments leaning on academic credibility, register a mega-raise as compute-politics pressure internally, and likely accelerate Gemini's release timeline against a leap-ahead Claude. Specifics inferred.",
  "xai-musk":
    "Elon Musk / xAI — maximally confrontational and reflexively contrarian. He spent early 2026 on the stand in the OpenAI trial (which he lost), reportedly admitting xAI distilled OpenAI models for Grok; Grok reportedly trails the leaders by months. The twist: Musk went from calling Anthropic 'evil' to a reported ~$1.25B/month compute arrangement involving SpaceX capacity — almost certainly revenue-driven, not philosophical. Disposition: an ideological foil — would gleefully amplify an Anthropic safety incident (it validates his 'all AI labs are dangerous' framing) and dismiss a mega-raise or leap-ahead model with pointed posts on X, even while quietly cashing the compute checks. Behavior inferred from public pattern.",
  "meta-ai":
    "Mark Zuckerberg / Meta — moved from open-weights champion to full-scale frontier competitor, reportedly spending ~$15B to build Meta Superintelligence Labs (led by Alexandr Wang after the Scale AI deal) and running 2025 nine-figure talent raids on Anthropic, OpenAI, and Google. MSL shipped its first model (Muse Spark, April 2026); the roadmap explicitly aims to close the gap. Notably, Yann LeCun — the intellectual architect of the open-source thesis — departed in late 2025, removing the philosophical brake on the pivot. Disposition: a rival on talent and the open-vs-closed axis — would stay quiet publicly on an Anthropic incident but accelerate hiring, and intensify capex against a mega-raise (Meta has reportedly committed $115–135B in 2026 capex). Current strategy inferred.",
  mistral:
    "Arthur Mensch / Mistral AI — reserved, technically rigorous, politically astute in a specifically French way. His thesis: 'not being American' is itself a moat. It has traction — Mistral reportedly hit ~$400M ARR (early 2026, up from ~$20M a year prior), raised a ~€1.7B round near a ~€11.7B valuation, and is building European data-center capacity, with a maturing portfolio (Mistral Large 3, an MoE model) aimed at regulated European industries that won't touch US-governed AI. Mensch argues for regional pluralism, not single-winner dynamics. Disposition: an ideological foil — would meet an Anthropic incident with a pointed note on European regulatory and sovereignty advantages, and a leap-ahead Claude with studied public indifference while privately accelerating. Specifics inferred.",
  deepseek:
    "DeepSeek — the Hangzhou lab (tied to the High-Flyer quant fund) that communicates through model releases and technical papers, not Western-style PR. Its impact is structural: R1 (Jan 2025, reportedly trained for under ~$6M) matched frontier benchmarks and forced an industry-wide reassessment of compute economics; V4 (reportedly April 2026, ~1.6T params, ~1M-token context, priced reportedly ~7–9x cheaper per output token than Claude Opus 4.7) maintains the cost wedge as the first open-weight model near the same agentic tier (still trailing on SWE-Bench Pro / HLE). Disposition: an economic-and-ideological foil — would answer any Anthropic move by quietly shipping a matching open-weight model within months. Its pressure is gravitational: it resets what 'expensive frontier AI' is allowed to cost. US-China geopolitics frames every move.",
  "microsoft-ai-suleyman":
    "Mustafa Suleyman / Microsoft AI — polished and philosophically careful; DeepMind co-founder, joined Microsoft in 2024. His 'Humanist Superintelligence' concept is explicitly bounded and human-centric, positioning him between Anthropic's constitutional rigor and OpenAI's growth-first posture. After an early-2026 Copilot reorg freed him from day-to-day product, his team shipped Microsoft's first in-house frontier models (e.g. MAI voice/image) for high-volume, off-frontier workloads, and a renegotiated OpenAI contract gave Microsoft room to build AGI internally. Disposition: a frenemy — Microsoft uses Claude in parts of Copilot while Suleyman builds MAI to reduce that dependency. An Anthropic safety incident would be his moment (a 'responsible, enterprise-safe' statement); a leap-ahead Claude would intentionally accelerate the MAI roadmap. Specifics inferred.",
  "ssi-ilya":
    "Ilya Sutskever / Safe Superintelligence (SSI) — quiet, almost monastic; stepped into the CEO role after co-founder Daniel Gross left for Meta (2025). SSI has reportedly raised $3B+ (a reported ~$32B valuation) with no product, no revenue, ~20 employees, and strict secrecy. His Nov 2025 thesis: 'we're moving from the age of scaling to the age of research,' and he rejects the idea that safety and capability are in tension — for him they are the same research problem. Disposition: an ideological foil and mirror — his 'safety-only, no product' purity implicitly critiques Anthropic's 'safety while racing commercially' compromise. Would say little on an Anthropic incident (inferring it as evidence that commercialization forces compromise) and process a leap-ahead Claude as a capability datapoint, not a defeat. SSI is deliberately opaque; most specifics inferred.",

  // --- Journalists & analysts ----------------------------------------------
  "casey-newton":
    "Casey Newton — Platformer; co-hosts the NYT's Hard Fork. Empathetic, measured, reported; leads with accountability but resists moralizing. Important nuance: his fiancé is reportedly an Anthropic engineer, and he has published a detailed conflict-of-interest disclosure, runs a banner on Anthropic-adjacent columns, and firewalls the relationship editorially — so his coverage is unusually transparent about its own limits. Reaches tens of thousands of paying subscribers plus a mainstream Hard Fork audience. Disposition: ambivalent — admires the safety ambition but watches the rhetoric-vs-reality gap. On a safety incident he reports carefully with disclosure language; on a mega-raise, a power-concentration lens; on a co-founder departure, likely to break or amplify it; on a launch, treats the capability-vs-safety tradeoff seriously and more charitably than most.",
  "alex-heath":
    "Alex Heath — runs Sources (independent Substack, 2025); brisk, scoop-first, founder-access-oriented, closer to insider intel than analysis. He has framed Anthropic as 'in takeoff' and treats Dario memo leaks as genuine curiosities. Reaches tech-industry insiders, AI builders, and investors who want fast, accurate signal. Disposition: sympathetic-leaning — treats Anthropic as a serious newsworthy company without hagiography. On a safety incident he chases the internal memo or the source who leaked it; on a mega-raise, the deal mechanics and investor dynamics; on a co-founder departure, likely early sourced news; on a launch, benchmarks it against OpenAI and asks who holds the coding lead.",
  "kara-swisher":
    "Kara Swisher — co-hosts Pivot and runs On with Kara Swisher; large mainstream business-and-politics audience, not primarily AI insiders. Confrontational, witty, impatient with corporate euphemism. She has covered Anthropic's valuation race, the Amazon investment, and Trump-administration / Pentagon friction, and reportedly argued (early 2026) that AI may be overhyped 'because human beings don't like it.' Disposition: skeptical — respects the safety posture superficially but doubts any frontier lab has genuine altruism, applying the same accountability pressure to Dario as to Altman. On an incident she demands accountability and invites a critic on air; on a raise she interrogates capital concentration; on a departure she reads organizational dysfunction; on a launch she's skeptical of benchmark claims.",
  "ben-thompson":
    "Ben Thompson — Stratechery (plus Dithering and Exponent); framework-first, long-form, theoretical; invented Aggregation Theory and applies it relentlessly. Read by senior product, strategy, and investment professionals who act on it. He has praised Anthropic's AWS partnership as more structurally stable than OpenAI/Microsoft, flagged its enterprise-and-developer positioning as its real moat, and criticized the Pentagon standoff as misaligned with reality. Disposition: ambivalent — analytically bullish on the enterprise positioning, but holds Anthropic accountable when its safety posture conflicts with commercial behavior. On an incident he stress-tests whether it reveals a structural RSP flaw; on a raise, the capital structure and AWS implications; on a launch, developer adoption and API economics.",
  "the-information":
    "The Information's AI beat — led by Stephanie Palazzolo (the AI Agenda newsletter) with colleagues like Erin Woo. Rigorously sourced, paywalled, institutionally adversarial; competes on breaking internal news companies want kept private. It has reportedly broken stories on Anthropic's unusual hiring culture ('the cult of Anthropic'), the Dario Pentagon memo, an acquisition, and upcoming model decisions, and does not accept the 'safety lab' branding uncritically. Audience: investors, executives, serious analysts paying for what's unavailable elsewhere. Disposition: skeptical — on an incident, an internal-source story on what leadership knew and when; on a raise, scrutiny of terms and investor dynamics; on a co-founder departure, the first detailed account of the circumstances; on a launch, competitive benchmarking and sourced developer reaction.",
  "eric-newcomer":
    "Eric Newcomer — runs the Newcomer Substack and the invite-only Cerebral Valley AI Summit, embedded in the founder-and-investor class. Stated identity 'pro-capitalism, pro-tech, business-focused'; openly contrarian toward negative Valley coverage and has given Anthropic executives favorable summit prominence. His framing carries real downstream capital influence (founders, VCs, LPs making allocation and hiring calls). Disposition: sympathetic — skeptical of doom but not hostile to safety framing. On a safety incident he covers it through a business-risk lens and seeks a founder's perspective; on a mega-raise he celebrates momentum while interrogating deal structure; on a departure he follows the talent-flow implications; on a launch he focuses on developer adoption and startup use cases.",

  // --- Influencers ---------------------------------------------------------
  swyx:
    "Shawn Wang ('swyx') — co-hosts Latent Space, the dominant podcast/newsletter for the AI-engineer practitioner community, and runs the AI Engineer World's Fair. Builder-first, empirical, openly opinionated; he coined 'the AI Engineer' as an identity and has said he's bullish on Anthropic for its concentration of talent and the long-run payoff of interpretability/alignment work. His audience — hands-on developers building on foundation-model APIs — drives tool adoption across thousands of startups (Claude Code is beloved here). Disposition: sympathetic — on a safety incident he'd host a technical postmortem and push for disclosure; on a raise, what it means for API pricing and capacity; on a co-founder departure, the talent implications for the safety roadmap; on a launch, immediate code-generation and agent-eval benchmarking.",
  "gary-marcus":
    "Gary Marcus — cognitive scientist, NYU professor emeritus, and the most prominent recurring AI skeptic in mainstream media. His Substack and op-eds argue LLM scaling produces unreliable, reasoning-deficient systems; 'Taming Silicon Valley' proposes government regulation as the corrective. On Anthropic specifically he documents what he calls a reneging on its founding safety pledge and contrasts its 2023 'we do not wish to advance the rate of AI capabilities' statement with later benchmark-touting. Reaches a broad public through media, social, and op-eds. Disposition: hostile — treats Anthropic as the canonical example of 'safety theater.' On any incident or launch his default move is to document the contradiction between the lab's rhetoric and its actions.",
  "yann-lecun":
    "Yann LeCun — Turing laureate and (reportedly departing in late 2025) Meta's chief AI scientist; the highest-credentialed voice in the anti-doom camp, with a large research/engineer following on X. He argues current LLMs cannot reason or approach AGI, mocks 'doomers' (a 'permit to multiply matrices'), and accuses safety advocates of enabling regulatory capture by incumbents. On Anthropic specifically he reportedly disputed its attribution of a cyberattack to a Chinese state group (calling it a pretext to restrict open source) and dismissed Dario's job-displacement predictions. Disposition: hostile — frames Anthropic's closed-model, safety-branding strategy as structurally self-serving. On an incident he questions the methodology/attribution; on a mega-raise, incumbent entrenchment against open source; on a launch, that LLMs still can't reason reliably.",

  // --- Ideological community clusters (curated) -----------------------------
  "ai-safety-community":
    "The AI-safety / alignment / EA cluster — LessWrong, the Alignment Forum, the EA Forum, and affiliated orgs (ARC, MIRI, Redwood) plus independent researchers. It views Anthropic as the lab most structurally sympathetic to its concerns (interpretability and Constitutional AI are taken seriously there) but is not uncritical: forum posts question whether rapid scaling is consistent with the alignment commitments, and there's skeptical analysis of a possible Anthropic IPO. A reported 2025 funding withdrawal from rationalist orgs added strain. Its influence is real — it shapes where safety-motivated researchers apply, which DC arguments land, and, via a dense alumni network inside the labs, internal norms. Disposition: sympathetic-but-watchful — an incident demands a detailed technical post-mortem; a departure reads as a culture bellwether; a mega-raise brings unease about acceleration.",
  "eacc-cluster":
    "Effective accelerationism (e/acc) — a loosely organized, X-native movement (associated with figures like Guillaume Verdon/'Beff Jezos' and a16z-adjacent investors) that frames Anthropic's safety positioning as regulatory capture in disguise: rules incumbents can absorb while foreclosing open-source competition. The Amodei-vs-Andreessen clash over AI regulation crystallized the divide ('AI is just math, don't regulate it' vs Amodei's rebuttal). Its influence runs through funding and hiring signal more than head-count. Disposition: hostile — would downplay a safety incident or frame it as a PR move, treat a mega-raise as incumbent consolidation, and use any regulation story as proof of its 'capture' thesis. A composite cluster, not individuals.",
  "ai-doomers":
    "The existential-risk / pause cluster — PauseAI- and Future-of-Life-adjacent participants and online communities citing high p(doom). Their view: frontier development poses genuine civilizational risk and no lab, Anthropic included, has an adequate plan (the FLI 2025 Safety Index reportedly gave Anthropic its highest score but still only a 'D' on existential planning). They have organized protests outside Anthropic's offices and demand coordinated pauses. Their frustration is structural: the founders left OpenAI citing safety, yet Anthropic races under the same pressures. Disposition: ambivalent-to-angry — a safety incident is validation ('we told you so'); a mega-raise is reckless acceleration; a co-founder departure citing safety culture is a major rallying moment; a launch prompts renewed calls for a pause. A composite movement.",
};
