import Link from "next/link";
import s from "../legal.module.css";

export const metadata = {
  title: "Terms of Service | Wake",
  description: "The terms for using Wake, including how to treat its output.",
};

export default function TermsPage() {
  return (
    <main className={s.page}>
      <div className={s.top}>
        <Link href="/" className={s.brand}>
          Wake<span className={s.dot}>.</span>
        </Link>
        <Link href="/" className={s.back}>
          ← Back to home
        </Link>
      </div>

      <h1 className={s.title}>Terms of Service</h1>
      <div className={s.updated}>Last updated May 25, 2026</div>

      <div className={s.prose}>
        <p className={s.lead}>
          By using Wake, you agree to these terms. Please read them, especially the part
          about how to treat Wake&apos;s output.
        </p>

        <h2>What Wake is</h2>
        <p>
          Wake is a simulation tool. You describe an action, and Wake uses AI to model
          how people, communities, and platforms might react, producing a distribution
          of possible outcomes along with the reasoning behind each.
        </p>

        <h2>Illustrative, not advice</h2>
        <p>
          This is the important part. Wake&apos;s output is illustrative and
          probabilistic. It is a map of what could happen, not a prediction of what will
          happen, and it is not professional, legal, financial, or strategic advice. The
          simulations are generated by AI and can be incomplete, biased, or simply wrong.
          You are responsible for your own decisions. Do not rely on Wake as the sole
          basis for any decision, and verify anything that matters independently.
        </p>

        <h2>People in simulations</h2>
        <p>
          Wake models composites and public roles to reason about likely reactions. It is
          not a tool for surveilling, profiling, or making defamatory claims about
          specific private individuals, and you agree not to use it that way.
        </p>

        <h2>Acceptable use</h2>
        <p>
          Don&apos;t use Wake to break the law, infringe others&apos; rights, or disrupt
          the service, and don&apos;t attempt to reverse engineer, overload, or scrape it.
        </p>

        <h2>Your API key and costs</h2>
        <p>
          If you bring your own Gemini API key, you are responsible for keeping it secure
          and for any usage costs Google charges you. See the{" "}
          <Link href="/privacy">Privacy Policy</Link> for how your key is handled.
        </p>

        <h2>No warranty</h2>
        <p>
          Wake is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without
          warranties of any kind, whether express or implied, including merchantability,
          fitness for a particular purpose, accuracy, and non-infringement. We do not
          warrant that the service will be uninterrupted, error free, or accurate.
        </p>

        <h2>Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, Wake and the people who make it are not
          liable for any indirect, incidental, special, or consequential damages, or for
          any loss arising from a decision you made with the help of the service.
        </p>

        <h2>Changes</h2>
        <p>
          We may update these terms as the product evolves. Continued use after a change
          means you accept the updated terms.
        </p>

        <h2>Contact</h2>
        <p>
          Questions? Reach us at <a href="mailto:hello@example.com">[your contact email]</a>.
        </p>
        <p className={s.note}>
          This is a plain-language starting template, provided in good faith, and is not
          legal advice. Have a lawyer review it before you rely on it.
        </p>
      </div>
    </main>
  );
}
